"use client";

import { useState, useMemo } from "react";
import type { ServiceCatalogItem, Client } from "@/types/database";
import { Beaker, Plus, Minus, Calculator, Copy, Check, DollarSign } from "lucide-react";

function currency(v: number) { return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(v); }

const svcColors: Record<string, string> = {
  Cloud: "svc-cloud svc-bg-cloud svc-border-cloud", Web: "svc-web svc-bg-web svc-border-web",
  Design: "svc-design svc-bg-design svc-border-design", Marketing: "svc-marketing svc-bg-marketing svc-border-marketing",
};

interface SelectedItem { catalogId: string; quantity: number; }

export function GeneratorLab({ catalog, clients }: { catalog: ServiceCatalogItem[]; clients: Pick<Client, "id" | "name">[] }) {
  const [selected, setSelected] = useState<SelectedItem[]>([]);
  const [entities, setEntities] = useState(1);
  const [integrations, setIntegrations] = useState(0);
  const [hourlyRate, setHourlyRate] = useState(150);
  const [copied, setCopied] = useState(false);

  const catalogMap = useMemo(() => Object.fromEntries(catalog.map((c) => [c.id, c])), [catalog]);
  const grouped = useMemo(() => {
    const g: Record<string, ServiceCatalogItem[]> = {};
    catalog.forEach((c) => { (g[c.service_type] ??= []).push(c); });
    return g;
  }, [catalog]);

  const lineItems = useMemo(() => selected.map((s) => {
    const item = catalogMap[s.catalogId];
    if (!item) return null;
    const price = Number(item.base_price) * Number(item.complexity_multiplier) * s.quantity;
    return { ...item, quantity: s.quantity, total: price };
  }).filter(Boolean) as (ServiceCatalogItem & { quantity: number; total: number })[], [selected, catalogMap]);

  const subtotal = lineItems.reduce((s, i) => s + i.total, 0);

  // Cost-of-Complexity: base complexity from entities/integrations
  const complexityScore = Math.max(1, entities * 0.3 + integrations * 0.5);
  const complexityMultiplier = 1 + (complexityScore - 1) * 0.15;
  const adjustedTotal = subtotal * complexityMultiplier;
  const minHoursEstimate = adjustedTotal / hourlyRate;

  const addItem = (id: string) => {
    setSelected((prev) => {
      const existing = prev.find((s) => s.catalogId === id);
      if (existing) return prev.map((s) => s.catalogId === id ? { ...s, quantity: s.quantity + 1 } : s);
      return [...prev, { catalogId: id, quantity: 1 }];
    });
  };

  const removeItem = (id: string) => {
    setSelected((prev) => {
      const existing = prev.find((s) => s.catalogId === id);
      if (!existing) return prev;
      if (existing.quantity <= 1) return prev.filter((s) => s.catalogId !== id);
      return prev.map((s) => s.catalogId === id ? { ...s, quantity: s.quantity - 1 } : s);
    });
  };

  const generateProposal = () => {
    const now = new Date().toISOString().split("T")[0];
    let md = `# Service Proposal\n\n**Date:** ${now}\n**Prepared by:** Venture OS\n\n---\n\n## Services\n\n| Service | Type | Qty | Unit Price | Total |\n|---------|------|-----|-----------|-------|\n`;
    lineItems.forEach((i) => {
      md += `| ${i.name} | ${i.service_type} | ${i.quantity} | ${currency(Number(i.base_price) * Number(i.complexity_multiplier))} | ${currency(i.total)} |\n`;
    });
    md += `\n---\n\n**Subtotal:** ${currency(subtotal)}\n`;
    md += `**Complexity Adjustment:** ×${complexityMultiplier.toFixed(2)} (${entities} entities, ${integrations} integrations)\n`;
    md += `**Total:** ${currency(adjustedTotal)}\n`;
    md += `**Estimated Hours:** ${minHoursEstimate.toFixed(0)}h @ ${currency(hourlyRate)}/hr\n\n---\n\n*Generated by Venture OS · Sovereign Foundation*\n`;

    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="flex flex-col h-full">
      <div className="h-14 border-b border-border flex items-center px-6 bg-card/40 backdrop-blur-sm shrink-0 gap-4">
        <Beaker className="w-4 h-4 text-primary" />
        <span className="text-sm font-bold text-foreground">Generator Lab</span>
        <span className="text-xs text-muted-foreground">Proposal & Cost Calculator</span>
      </div>

      <div className="flex-1 overflow-y-auto p-6 fade-in">
        <div className="grid grid-cols-5 gap-5">

          {/* ─── Catalog (Left) ────────────────────────────────── */}
          <div className="col-span-3 space-y-4">
            <h2 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">Service Catalog</h2>
            {Object.entries(grouped).map(([type, items]) => (
              <div key={type}>
                <div className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground/50 mb-2">{type}</div>
                <div className="grid grid-cols-2 gap-2.5">
                  {items.map((item) => {
                    const qty = selected.find((s) => s.catalogId === item.id)?.quantity ?? 0;
                    const sv = svcColors[item.service_type] ?? "";
                    return (
                      <div key={item.id} className={`glass-card p-4 ${qty > 0 ? "border-primary/25" : ""}`}>
                        <div className="flex items-center justify-between mb-2">
                          <span className={`text-[9px] font-semibold px-1.5 py-0.5 rounded border ${sv}`}>{item.service_type}</span>
                          <span className="text-xs font-bold text-foreground">{currency(Number(item.base_price))}</span>
                        </div>
                        <div className="text-sm font-medium text-foreground mb-1">{item.name}</div>
                        <div className="text-[11px] text-muted-foreground/60 mb-3 line-clamp-2">{item.description}</div>
                        <div className="flex items-center gap-2">
                          <button onClick={() => removeItem(item.id)} className="w-7 h-7 rounded-lg bg-accent hover:bg-accent/80 flex items-center justify-center transition-colors">
                            <Minus className="w-3 h-3 text-muted-foreground" />
                          </button>
                          <span className="text-sm font-bold text-foreground w-6 text-center">{qty}</span>
                          <button onClick={() => addItem(item.id)} className="w-7 h-7 rounded-lg bg-primary/15 hover:bg-primary/25 flex items-center justify-center transition-colors">
                            <Plus className="w-3 h-3 text-primary" />
                          </button>
                          <span className="text-[10px] text-muted-foreground ml-auto">×{Number(item.complexity_multiplier).toFixed(1)}</span>
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            ))}
          </div>

          {/* ─── Calculator (Right) ────────────────────────────── */}
          <div className="col-span-2 space-y-4">
            {/* Cost-of-Complexity */}
            <div className="glass-card p-5">
              <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-3 flex items-center gap-2">
                <Calculator className="w-3.5 h-3.5" /> Cost-of-Complexity
              </h3>
              <div className="space-y-3">
                <div>
                  <label className="text-[10px] text-muted-foreground/60 block mb-1">Entities</label>
                  <input type="number" min={1} value={entities} onChange={(e) => setEntities(Number(e.target.value) || 1)}
                    className="w-full h-8 px-3 bg-accent border border-border rounded-lg text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-primary/30" />
                </div>
                <div>
                  <label className="text-[10px] text-muted-foreground/60 block mb-1">Integrations</label>
                  <input type="number" min={0} value={integrations} onChange={(e) => setIntegrations(Number(e.target.value) || 0)}
                    className="w-full h-8 px-3 bg-accent border border-border rounded-lg text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-primary/30" />
                </div>
                <div>
                  <label className="text-[10px] text-muted-foreground/60 block mb-1">Hourly Rate ($)</label>
                  <input type="number" min={1} value={hourlyRate} onChange={(e) => setHourlyRate(Number(e.target.value) || 100)}
                    className="w-full h-8 px-3 bg-accent border border-border rounded-lg text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-primary/30" />
                </div>
                <div className="pt-2 border-t border-border/40">
                  <div className="flex items-center justify-between text-xs">
                    <span className="text-muted-foreground">Complexity Score</span>
                    <span className="font-bold text-foreground">{complexityScore.toFixed(1)}</span>
                  </div>
                  <div className="flex items-center justify-between text-xs mt-1">
                    <span className="text-muted-foreground">Multiplier</span>
                    <span className="font-bold text-foreground">×{complexityMultiplier.toFixed(2)}</span>
                  </div>
                </div>
              </div>
            </div>

            {/* Proposal Summary */}
            <div className="glass-card p-5">
              <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-3 flex items-center gap-2">
                <DollarSign className="w-3.5 h-3.5" /> Proposal Summary
              </h3>
              {lineItems.length === 0 ? (
                <p className="text-xs text-muted-foreground/50 py-4 text-center">Add services from the catalog →</p>
              ) : (
                <div className="space-y-2 mb-4">
                  {lineItems.map((item, i) => (
                    <div key={i} className="flex items-center justify-between py-1.5 border-b border-border/20 last:border-0">
                      <span className="text-xs text-foreground">{item.name} ×{item.quantity}</span>
                      <span className="text-xs font-bold text-foreground">{currency(item.total)}</span>
                    </div>
                  ))}
                </div>
              )}

              <div className="space-y-1.5 pt-3 border-t border-border/40">
                <div className="flex justify-between text-xs">
                  <span className="text-muted-foreground">Subtotal</span>
                  <span className="font-medium text-foreground">{currency(subtotal)}</span>
                </div>
                <div className="flex justify-between text-xs">
                  <span className="text-muted-foreground">Complexity ×{complexityMultiplier.toFixed(2)}</span>
                  <span className="font-medium text-foreground">{currency(adjustedTotal - subtotal)}</span>
                </div>
                <div className="flex justify-between text-sm pt-2 border-t border-border/40">
                  <span className="font-bold gradient-text-gold">Total</span>
                  <span className="font-bold text-lg gradient-text-gold">{currency(adjustedTotal)}</span>
                </div>
                <div className="flex justify-between text-xs mt-1">
                  <span className="text-muted-foreground">Min Hours</span>
                  <span className="text-foreground">{minHoursEstimate.toFixed(0)}h @ {currency(hourlyRate)}/hr</span>
                </div>
              </div>

              <button onClick={generateProposal} disabled={lineItems.length === 0}
                className="w-full mt-4 h-10 btn-gradient flex items-center justify-center gap-2 text-sm disabled:opacity-30 disabled:cursor-not-allowed">
                {copied ? <><Check className="w-4 h-4" /> Copied to Clipboard</> : <><Copy className="w-4 h-4" /> Generate Proposal (MD)</>}
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
